# Generated by Django 6.0.3 on 2026-03-11 07:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Room number inside the ward', max_length=20)),
                ('room_type', models.CharField(choices=[('PRIVATE', 'Private Room'), ('SHARED', 'Shared Room'), ('ISOLATION', 'Isolation Room'), ('OBSERVATION', 'Observation Room')], default='SHARED', max_length=20)),
                ('capacity', models.IntegerField(help_text='Maximum number of beds in this room', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='wards.ward')),
            ],
            options={
                'ordering': ['room_number'],
                'indexes': [models.Index(fields=['room_number'], name='rooms_room_room_nu_914a74_idx')],
                'constraints': [models.UniqueConstraint(fields=('ward', 'room_number'), name='unique_room_in_ward')],
            },
        ),
    ]
