# Generated by Django 6.0.3 on 2026-03-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_password_reset_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('RESET', 'Reset'), ('ADMIN', 'Admin')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
