# Generated by Django 6.0.3 on 2026-03-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_resettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_verified',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('LOGIN', 'Login')], max_length=10),
        ),
    ]
