# Generated by Django 6.0.3 on 2026-04-03 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('NORMAL', 'Normal'), ('CRITICAL', 'Critical'), ('RECOVERY', 'Recovery')], db_index=True, default='NORMAL', max_length=20)),
                ('trend', models.CharField(choices=[('STABLE', 'Stable'), ('WORSENING', 'Worsening'), ('IMPROVING', 'Improving')], db_index=True, default='STABLE', max_length=20)),
                ('heart_rate_min', models.IntegerField(default=60)),
                ('heart_rate_max', models.IntegerField(default=100)),
                ('spo2_min', models.IntegerField(default=95)),
                ('spo2_max', models.IntegerField(default=100)),
                ('systolic_bp_min', models.IntegerField(default=110)),
                ('systolic_bp_max', models.IntegerField(default=130)),
                ('diastolic_bp_min', models.IntegerField(default=70)),
                ('diastolic_bp_max', models.IntegerField(default=90)),
                ('respiratory_rate_min', models.IntegerField(default=12)),
                ('respiratory_rate_max', models.IntegerField(default=20)),
                ('temperature_min', models.FloatField(default=36.5)),
                ('temperature_max', models.FloatField(default=37.5)),
                ('auto_reset', models.BooleanField(default=True)),
                ('reset_interval', models.IntegerField(default=300, help_text='Seconds before resetting simulation state')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
