# Generated by Django 6.0.3 on 2026-04-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationconfig',
            name='variability',
            field=models.FloatField(default=0.05, help_text='Random noise factor (e.g. 0.05 = 5% noise)'),
        ),
    ]
