# Generated by Django 6.0.3 on 2026-04-20 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_device_simulation_config_device_last_dia_and_more'),
        ('simulation', '0002_simulationconfig_variability'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationconfig',
            name='device',
            field=models.OneToOneField(blank=True, help_text='The hardware unit this configuration applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_config', to='devices.device'),
        ),
    ]
