# Generated by Django 6.0.3 on 2026-05-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_simulationconfig_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationconfig',
            name='respiratory_rate_max',
        ),
        migrations.RemoveField(
            model_name='simulationconfig',
            name='respiratory_rate_min',
        ),
    ]
