# Generated by Django 6.0.3 on 2026-03-11 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=50, unique=True)),
                ('device_type', models.CharField(choices=[('ICU_MONITOR', 'ICU Monitor'), ('PORTABLE_MONITOR', 'Portable Monitor'), ('WEARABLE_SENSOR', 'Wearable Sensor')], default='ICU_MONITOR', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time the device sent data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.OneToOneField(help_text='Device assigned to a specific bed', on_delete=django.db.models.deletion.CASCADE, related_name='device', to='beds.bed')),
            ],
            options={
                'ordering': ['device_id'],
                'indexes': [models.Index(fields=['device_id'], name='devices_dev_device__e2c19e_idx'), models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx')],
            },
        ),
    ]
