# Generated by Django 6.0.3 on 2026-04-03 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_alter_bed_options_and_more'),
        ('devices', '0003_alter_device_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='simulation_mode',
            field=models.CharField(choices=[('GLOBAL', 'Use Global Config'), ('NORMAL', 'Normal'), ('CRITICAL', 'Critical'), ('RECOVERY', 'Recovery')], db_index=True, default='GLOBAL', help_text='Override global simulation mode per device', max_length=20),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['simulation_mode'], name='devices_dev_simulat_5232e6_idx'),
        ),
    ]
