# Generated by Django 6.0.3 on 2026-04-03 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_alter_bed_options_and_more'),
        ('devices', '0004_device_simulation_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mode',
            field=models.CharField(choices=[('REAL', 'Real Device'), ('SIMULATION', 'Simulation Device')], db_index=True, default='REAL', help_text='Defines if device is real or simulation', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='simulation_mode',
            field=models.CharField(choices=[('GLOBAL', 'Use Global Config'), ('NORMAL', 'Normal'), ('CRITICAL', 'Critical'), ('RECOVERY', 'Recovery')], db_index=True, default='GLOBAL', help_text='Override simulation behavior per device', max_length=20),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['mode'], name='devices_dev_mode_3b062f_idx'),
        ),
    ]
