# Generated by Django 6.0.3 on 2026-03-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_patient_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-admission_date']},
        ),
    ]
