# Generated by Django 6.0.3 on 2026-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_doctor_patient_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mode',
            field=models.CharField(choices=[('SIMULATION', 'Simulation'), ('REAL', 'Real Device')], default='SIMULATION', help_text='DEPRECATED: System now respects Device.mode as the single source of truth.', max_length=20),
        ),
    ]
