# Generated by Django 6.0.3 on 2026-04-24 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='primary_nurse',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'NURSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
