# Generated by Django 6.0.3 on 2026-05-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patient_last_condition_update_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ai_condition_summary',
            field=models.TextField(blank=True, help_text='ML-generated clinical summary based on telemetry trends.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_ai_assessment',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the latest Scikit-Learn assessment.', null=True),
        ),
    ]
