# Generated by Django 6.0.3 on 2026-05-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_patient_ai_condition_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='clinical_condition',
            field=models.CharField(choices=[('STABLE', 'Stable'), ('CRITICAL', 'Critical')], default='STABLE', help_text='Authoritative clinical status set by a physician.', max_length=20),
        ),
    ]
