# Generated by Django 6.0.3 on 2026-03-11 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('floor', models.IntegerField(help_text='Floor number where the ward is located', validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'ordering': ['floor'],
                'indexes': [models.Index(fields=['floor'], name='wards_ward_floor_75acc6_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'floor'), name='unique_ward_floor')],
            },
        ),
    ]
