# Generated by Django 6.0.3 on 2026-04-24 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0002_ward_created_by_ward_deleted_at_ward_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='nurses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'NURSE'}, related_name='assigned_wards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NurseShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_type', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether this shift is currently receiving telemetry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'NURSE'}, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='wards.ward')),
            ],
            options={
                'verbose_name': 'Nurse Shift',
                'verbose_name_plural': 'Nurse Shifts',
                'ordering': ['-start_time'],
            },
        ),
    ]
