# Generated by Django 6.0.3 on 2026-03-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_verified',
            field=models.BooleanField(default=False, help_text='OTP verified for password reset'),
        ),
    ]
