# Generated by Django 6.0.3 on 2026-04-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_license_number_user_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='token',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
