# Generated by Django 6.0.3 on 2026-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_otp_otp_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_connections',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
