# Generated by Django 6.0.3 on 2026-04-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_active_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid')], db_index=True, default='pending', max_length=10),
        ),
    ]
