# Generated by Django 6.0.3 on 2026-04-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('RESET', 'Reset Password'), ('EMAIL_CHANGE', 'Email Change Verification')], max_length=20),
        ),
    ]
