# Generated by Django 6.0.3 on 2026-03-26 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_alter_bed_options_and_more'),
        ('devices', '0002_alter_device_options_device_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['serial_number'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_device_per_bed',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='devices_dev_device__e2c19e_idx',
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(db_index=True, default='DEV-000', help_text='Unique device serial number', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('ICU_MONITOR', 'ICU Monitor'), ('PATIENT_MONITOR', 'Patient Monitor'), ('WEARABLE_SENSOR', 'Wearable Sensor'), ('SIMULATOR', 'Simulator')], default='PATIENT_MONITOR', max_length=30),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='devices_dev_serial__4a3e3a_idx'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
    ]
