# Generated by Django 6.0.3 on 2026-04-20 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_mode_alter_device_simulation_mode_and_more'),
        ('simulation', '0002_simulationconfig_variability'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='simulation_config',
            field=models.OneToOneField(blank=True, help_text='Custom simulation parameters for this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='simulation.simulationconfig'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('ICU_MONITOR', 'ICU Monitor'), ('PATIENT_MONITOR', 'Patient Monitor'), ('WEARABLE_SENSOR', 'Wearable Sensor')], default='PATIENT_MONITOR', max_length=30),
        ),
    ]
