# Generated by Django 6.0.3 on 2026-04-20 07:08

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_alter_bed_options_and_more'),
        ('devices', '0006_device_simulation_config_alter_device_device_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='simulation_config',
        ),
        migrations.AddField(
            model_name='device',
            name='last_dia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_hr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_rr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_simulated_at',
            field=models.DateTimeField(blank=True, help_text='Last time simulation logic ran', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_spo2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_sys',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='bed',
            field=models.OneToOneField(blank=True, help_text='Device assigned to bed (Optional for staging)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='beds.bed'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('serial_number'), name='unique_serial_number_case_insensitive'),
        ),
    ]
