# Generated by Django 6.0.3 on 2026-04-20 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_alter_bed_options_and_more'),
        ('devices', '0007_remove_device_simulation_config_device_last_dia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='monitor_label',
            field=models.CharField(blank=True, help_text='Clinician-friendly name (e.g. ICU-MONITOR-01)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='bed',
            field=models.OneToOneField(blank=True, help_text='Device assigned to bed (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='beds.bed'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_simulated_at',
            field=models.DateTimeField(blank=True, help_text='Last simulation run time', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mode',
            field=models.CharField(choices=[('REAL', 'Real Device'), ('SIMULATION', 'Simulation Device')], db_index=True, default='REAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='simulation_mode',
            field=models.CharField(choices=[('GLOBAL', 'Use Global Config'), ('NORMAL', 'Normal'), ('CRITICAL', 'Critical'), ('RECOVERY', 'Recovery')], db_index=True, default='GLOBAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_simulated_at'], name='devices_dev_last_si_bda138_idx'),
        ),
    ]
