# Generated by Django 6.0.3 on 2026-04-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_device_monitor_label_alter_device_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_key',
            field=models.CharField(blank=True, help_text='Secure API key for hardware authentication', max_length=100, null=True),
        ),
    ]
