# Generated by Django 6.0.3 on 2026-04-23 05:37

import apps.devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_device_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='api_key',
            field=models.CharField(db_index=True, default=apps.devices.models.generate_api_key, help_text='Secure API key for hardware authentication', max_length=100, unique=True),
        ),
    ]
