# Generated by Django 6.0.3 on 2026-04-23 05:53

import apps.devices.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_device_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_key_revoked',
            field=models.BooleanField(default=False, help_text='Hard block on all authentication for this device'),
        ),
        migrations.AddField(
            model_name='device',
            name='key_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the current API key was generated'),
        ),
        migrations.AddField(
            model_name='device',
            name='key_expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiration for the current key', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='previous_api_key',
            field=models.CharField(blank=True, help_text='Fallback key used during rotation grace period', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='api_key',
            field=models.CharField(db_index=True, default=apps.devices.models.generate_api_key, help_text='Current active key for hardware authentication', max_length=100, unique=True),
        ),
    ]
