# Generated by Django 6.0.3 on 2026-03-26 08:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_options_and_more'),
        ('patients', '0004_alter_patient_bed'),
        ('vitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vital',
            options={'ordering': ['-recorded_at'], 'verbose_name': 'Vital', 'verbose_name_plural': 'Vitals'},
        ),
        migrations.RemoveIndex(
            model_name='vital',
            name='vitals_vita_patient_c9b49e_idx',
        ),
        migrations.AddField(
            model_name='vital',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vital',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vital',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vital',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vital',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='vital',
            name='heart_rate',
            field=models.IntegerField(help_text='Heart rate (bpm)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)]),
        ),
        migrations.AlterField(
            model_name='vital',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='vital',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vital',
            name='spo2',
            field=models.IntegerField(help_text='Oxygen saturation (%)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vital',
            name='temperature',
            field=models.FloatField(help_text='Body temperature (C)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(45)]),
        ),
        migrations.AddIndex(
            model_name='vital',
            index=models.Index(fields=['device', 'recorded_at'], name='vitals_vita_device__a169d4_idx'),
        ),
    ]
