# Generated by Django 6.0.3 on 2026-04-23 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_device_is_key_revoked_device_key_created_at_and_more'),
        ('patients', '0006_alter_patient_mode'),
        ('vitals', '0003_vital_source_vital_vitals_vita_source_12cb8e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hr_min', models.IntegerField()),
                ('hr_max', models.IntegerField()),
                ('hr_avg', models.FloatField()),
                ('spo2_min', models.IntegerField()),
                ('spo2_max', models.IntegerField()),
                ('spo2_avg', models.FloatField()),
                ('rr_avg', models.FloatField()),
                ('temp_avg', models.FloatField()),
                ('systolic_avg', models.FloatField()),
                ('diastolic_avg', models.FloatField()),
                ('data_type', models.CharField(default='REAL', max_length=20)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='devices.device')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', 'recorded_at'], name='vitals_vita_device__c5ec06_idx'), models.Index(fields=['data_type'], name='vitals_vita_data_ty_53c594_idx')],
            },
        ),
        migrations.CreateModel(
            name='VitalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hr_min', models.IntegerField()),
                ('hr_max', models.IntegerField()),
                ('hr_avg', models.FloatField()),
                ('spo2_min', models.IntegerField()),
                ('spo2_max', models.IntegerField()),
                ('spo2_avg', models.FloatField()),
                ('data_type', models.CharField(default='REAL', max_length=20)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='devices.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', 'recorded_at'], name='vitals_vita_device__83a13d_idx')],
            },
        ),
    ]
