# Generated by Django 6.0.3 on 2026-05-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0006_alter_vital_diastolic_bp_alter_vital_heart_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vital',
            name='respiratory_rate',
        ),
        migrations.RemoveField(
            model_name='vitalarchive',
            name='rr_avg',
        ),
    ]
