# Generated by Django 6.0.3 on 2026-03-26 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_alter_bed_options_and_more'),
        ('patients', '0003_alter_patient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='beds.bed'),
        ),
    ]
