# Generated by Django 6.0.3 on 2026-03-25 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
        ('rooms', '0002_alter_room_options_room_created_by_room_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['bed_number'], 'verbose_name': 'Bed', 'verbose_name_plural': 'Beds'},
        ),
        migrations.RemoveIndex(
            model_name='bed',
            name='beds_bed_bed_num_4ff1de_idx',
        ),
        migrations.AddField(
            model_name='bed',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bed',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bed',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='rooms.room'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['room'], name='beds_bed_room_id_f5d102_idx'),
        ),
    ]
