# Generated by Django 6.0.3 on 2026-03-11 08:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(help_text='Heart rate in beats per minute', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)])),
                ('spo2', models.IntegerField(help_text='Oxygen saturation percentage', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('respiratory_rate', models.IntegerField(help_text='Breaths per minute', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('temperature', models.FloatField(help_text='Body temperature in Celsius', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(45)])),
                ('systolic_bp', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('diastolic_bp', models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)])),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals', to='devices.device')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient'], name='vitals_vita_patient_8cb606_idx'), models.Index(fields=['device'], name='vitals_vita_device__2f00dd_idx'), models.Index(fields=['recorded_at'], name='vitals_vita_recorde_564d1e_idx'), models.Index(fields=['patient', 'recorded_at'], name='vitals_vita_patient_c9b49e_idx')],
            },
        ),
    ]
