# Generated by Django 6.0.3 on 2026-04-03 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_mode_alter_device_simulation_mode_and_more'),
        ('patients', '0005_patient_doctor_patient_mode'),
        ('vitals', '0002_alter_vital_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='source',
            field=models.CharField(choices=[('DEVICE', 'Real Device'), ('SIMULATION', 'Simulation Engine')], db_index=True, default='DEVICE', help_text='Source of vitals data', max_length=20),
        ),
        migrations.AddIndex(
            model_name='vital',
            index=models.Index(fields=['source'], name='vitals_vita_source_12cb8e_idx'),
        ),
        migrations.AddIndex(
            model_name='vital',
            index=models.Index(fields=['patient', 'recorded_at'], name='vitals_vita_patient_c9b49e_idx'),
        ),
    ]
